

version: '2.0'
webpro:
  restart: always
  build: ./project
  ports:
    - "7001:7001"
  volumes:
    - ./project:/src
  environment:
    - EGG_SERVER_ENV=production
    - PORT=7001
  links:
    - redis
    - mysql
    - mongo
redis:
  restart: always
  image: redis
  ports:
    - "6379"
  volumes:
    - ./db/redis:/src
  links:
    - mysql
mysql:
  restart: always
  image: mysql
  ports:
    - "3306"
  volumes:
    - ./db/mysql:/docker-entrypoint-initdb.d
    - ./db/mysqlData:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

mongo:
    restart: always
    image: mongo
    ports:
      - "27017"
    volumes:
      - /db/mongo